Update chart-tagger.yaml

diff --git a/.github/workflows/chart-tagger.yaml b/.github/workflows/chart-tagger.yaml
--- a/.github/workflows/chart-tagger.yaml
+++ b/.github/workflows/chart-tagger.yaml
@@ -61,6 +61,24 @@ jobs:
                   labels: |
                     automated pr
 
+    
+            - name: Start release
+              run: |
+                response=$(curl -X POST \
+                    -H "Content-Type: application/json" \
+                    https://yfoa5flvfk.execute-api.us-east-1.amazonaws.com/staging/start-release \
+                    -d '{
+                        "repo": "${{ github.repository.name }}",
+                        "sha": "${{ steps.cpr.outputs.pull-request-head-sha }}",
+                        "release_id": "${{ needs.generate-release-tag.outputs.release_tag }}"
+                    }')
+                    echo "Response: $response"
+                    status=$(echo "$response" | jq -r '.status')
+                    if [ "$status" -ne 200 ]; then
+                      echo "Error: API call failed with status $status"
+                      exit 1
+                    fi
+
     # port-logs:
     #     if: success() || failure()
     #     needs: [ update-helm-chart ]
